### ISSUE TITLE
Import CSS once in src/index.js

### ISSUE THREAD

**Issue by cliftondavies** [cliftondavies/Restaurant#6]
A good convention to follow.

**Comment by ucusita** [comment]
I will propose an update for this issue. It´s my first pull request, please give me a feedback.

**Comment by ucusita** [comment]
@cliftondavies Good morning, can you give a feedback about this, please, It´s my first Issue. Thanks

**Comment by cliftondavies** [comment]
Hi @ucusita! Thanks for reaching out, and sorry for the delay in responding. I have left a comment on your pull request.
